swagger: "2.0"
info:
  title: "API Consulta Pessoas"
  description: "API para consultar pessoas em listas"
  version: 1.0.0
host: "localhost:8000"
basePath: /api/
schemes:
  - http
paths:
  /consulta_nome:
    post:
      summary: "Retorna um JSON com resultado da consulta"
      description: ""
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/response"
definitions:
  response:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
